library(dplyr)
data <- read.table("household_power_consumption.txt",header=TRUE, sep=";")
dp <- tbl_df(data)
chida <- filter(dp,Date %in% c("1/2/2007","2/2/2007"))
ft <- strptime(paste(chida$Date, chida$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
q <- as.numeric(as.character(chida$Sub_metering_1))
qq <- as.numeric(as.character(chida$Sub_metering_2))
qqq <- as.numeric(as.character(chida$Sub_metering_3))
png("plot3.png", width=480, height=480)
plot(ft,q, type="n",xlab=" ",ylab="Energy sub metering")
lines(ft,q)
lines(ft,qq,col = "red")
lines(ft,qqq,col = "blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,lwd=2)
dev.off()